apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: leave-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: your-registry/leave-tracker-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: leave-tracker-secrets
              key: SLACK_BOT_TOKEN
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: leave-tracker-secrets
              key: SLACK_SIGNING_SECRET
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: leave-tracker-secrets
              key: SLACK_APP_TOKEN
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: leave-tracker-secrets
              key: SUPABASE_URL
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: leave-tracker-secrets
              key: SUPABASE_KEY
        - name: ADMIN_USER_ID
          valueFrom:
            secretKeyRef:
              name: leave-tracker-secrets
              key: ADMIN_USER_ID
        - name: FLASK_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5