apiVersion: v1
kind: Secret
metadata:
  name: leave-tracker-secrets
  namespace: leave-tracker
type: Opaque
data:
  # Encode your secrets in base64
  # echo -n "your-token" | base64
  SLACK_BOT_TOKEN: "eG94Yi01NDA5OTY3Njc0MDE2LTk3NjYyMjk5MzgwODYtMkp1dFQ3R3FENzhDN3lIVTgzNk53NlZq"
  SLACK_SIGNING_SECRET: "YTZhYmE5YzMzYTliZWJiNzVjMzgxZmMxMjQzNGJhZWU="
  SLACK_APP_TOKEN: "eGFwcC0xLUEwOU5ESjVQNjRULTk3NTI4MTU4ODYyNjMtMTYzNjQ4M2VlODBjYzVlZWU4ZjdkYzMyOTBkODUyMzlkMjcyMmMxMjljMGVmYjhjMzZkMWJiNTFiY2U5OGUxMw=="
  SUPABASE_URL: "https://nuejucyoktgzzcfgsjcj.supabase.co"
  SUPABASE_KEY: "ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW01MVpXcDFZM2x2YTNSbmVucGpabWR6YW1OcUlpd2ljbTlzWlNJNkluTmxjblpwWTJWZmNtOXNaU0lzSW1saGRDSTZNVGMwTlRrME1EazVOeXdpWlhod0lqb3lNRFl4TlRFMk9UazNmUS5hYTNyZlA0RFNVb1BTdjlFNjVUanpNdjRLbnYtRWFiT3R6YWdjQU00djVNCg=="
  ADMIN_USER_ID: "U05B99HGLAZ"