apiVersion: v1
kind: Secret
metadata:
  name: leave-tracker-secrets
  namespace: leave-tracker
type: Opaque
data:
  SLACK_BOT_TOKEN: <base64-encoded-token>
  SLACK_SIGNING_SECRET: <base64-encoded-secret>
  SLACK_APP_TOKEN: <base64-encoded-app-token>
  SUPABASE_URL: <base64-encoded-url>
  SUPABASE_KEY: <base64-encoded-key>
  ADMIN_USER_ID: <base64-encoded-admin-id>
  NGROK_AUTHTOKEN: <base64-encoded-ngrok-token>