apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: leave-tracker
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ngrok-service
  namespace: leave-tracker
spec:
  selector:
    app: ngrok
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
  type: LoadBalancer